server:
    port: 8080
spring:
    application:
        name: Health-Check-LoadBalancer

#健康检查
health:
    check:
        allow-partial-success: true # 是否将HTTP错误视为健康
        consider-http-errors-healthy: true # 是否允许部分成功（如206）
        interval: 30000 # 30秒检测间隔
        max-failures: 2 # 失败阈值
        recovery-interval: 60000 # 3分钟恢复检测间隔
        recovery-threshold: 1 # 增加恢复阈值
    #配置HTTP链接参数
    restTemplate:
        connectionRequestTimeout: 500
        connectionTimeout: 500 # 连接超时(毫秒)
        poolLimit: 800
        routerLimit: 100
        socketTimeout: 500

#负载均衡策略
loadbalancer:
    strategy: weighted #weighted权重轮询，round-robin轮询，random随机

banks:
    common:
        baseUrls:
            - http://wwww.baidu.com
            - http://wwww.bing.com
    configs:
        1001: { bankName: 杭州银行, path: hangzhou, weights: [3,1] }
        1002: { bankName: 工商银行, path: icbc, weights: [2,2] }
        1003: { bankName: 建设银行, path: ccb }
        1004: { bankName: 农业银行, path: abc, weights: [4,1] }
        1005:
            bankName: 特殊银行
            urls: # 覆盖自动生成
                - url: http://wwww.baidu.com
                  weight: 5
                - url: http://wwww.bing.com
                  weight: 1

#日志配置
logging:
    level:
        com:
            example:
                healthcheck: DEBUG
        root: INFO
